# Generated by Django 5.0.1 on 2024-01-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wateringcan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
