# Generated by Django 5.0.1 on 2024-01-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wateringcan', '0002_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
